#+Title: Automated Repair of Exploits in NETGEAR Router Binary
#+Author:
#+Options: ^:{}
#+HTML_Head: <link rel="stylesheet" type="text/css" href="../etc/netgear-repair.css" />
#+LaTeX_Class: sigcomm-alternative
#+LaTeX: \usetikzlibrary{arrows,decorations,decorations.pathreplacing,shapes}

#+LaTeX: \begin{abstract}
Upon discovering a software exploit security researchers must decide
either to publish the exploit informing users and potential attackers,
or to privately inform the software vendor leaving users in the dark
and risking delay by the vendor.  We propose an alternative in which
researchers use the newly discovered exploits to drive an automated
repair technique capable of patching exploits with no access to source
code or special information from the software vendor.

We adapt existing evolutionary automated software repair techniques to
the special requirements of exploit repair.  We adapt the technique to
work on stripped MIPS ELF files, we remove the requirements for fault
localization information and we adapt the algorithm to work without
any pre-existing regression test suite.  We find that even without any
regression test suite 80% of repairs of our example exploit retain
program functionality.

We demonstrate this approach by patching recently discovered exploits
in version 4 of NETGEAR's WNDR3700 wireless router /before/ NETGEAR
publicly addressed the exploits---to the author's knowledge NETGEAR
has not patched these exploits at the time of submission.  We discuss
the feasibility and utility of this technique for the security
community.
#+LaTeX: \end{abstract}

# The tooling and technique demonstrated herein are available under
# open source licensing [fn:1] and may be generalized to other
# embedded binary executables and reproducible exploits increasing the
# options available to security researchers upon discovering new
# exploits.

* Introduction
Security exploits pose significant monetary and social risks.  By
Symantec's count 5,291 vulnerabilities were reported in 2012
cite:symantec2013threat.

Upon discovering new exploits researchers are faced with a decision
between publicly announcing the exploit in a policy known as "full
disclosure" or privately informing the vendor of the exploit and
trusting the vendor to address the problem.  Although "full
disclosure" may increase attacks in the short term (In 2002, special
advisor for cyberspace security to then President Bush, Richard Clarke
said "It is irresponsible and... extremely damaging to release
information before the patch is out") there are risks associated with
informing vendors as well (e.g., Oracle reportedly waited months after
researchers privately reported a bug in Java while thousands of users
were attacked before releasing a fix cite:greenberg2012oracle).

We propose a new option for security researchers in which reproducible
exploits are used to drive an automatic repair technique.  Such
patches may be either published with the exploit (it has been shown
that reporting an exploit with a patch in hand reduces the total
number of attacks cite:arora2006does), or sent privately to the
software vendor where they may speed the development of a patch
cite:weimer06.

In recent years automated methods of program repair have been shown
capable of repairing defects in real software cite:forrest2009genetic
cite:zeller2010 cite:nguyen2013semfix cite:perkins2009automatically.
Methods of evolutionary program repair have been developed which are
capable of repairing defects directly in x86 or ARM ELF files and
which require no access to program source code
cite:schulte2013embedded.  We adapt evolutionary program repair
techniques to the unique needs of security researchers who have no
access to either source code or to a regression test suite, and who
are generating repairs without any special information or cooperation
from the software vendor.  Although evolutionary program repair
techniques typically require access to a regression test suite, we
explore the feasibility of performing repair without any such test
suite and find that for our example exploit regression test suites are
most often not necessary.

We demonstrate the feasibility of this technique by patching security
vulnerabilities in the widely popular NETGEAR WNDR3700 wireless router
before NETGEAR publicly addressed the exploits.

In the remainder of this paper we; review two recent exploits to the
NETGEAR WNDR3700 (Section [[#exploits]]), we demonstrate the feasibility
of running the NETGEAR firmware in a VM sandbox (Section [[#firmware]]),
we review our novel techniques of automated program repair (Sections
[[#mips-mutation]] and [[#lazy]]), and we evaluate the effectiveness of this
technique and the quality of the repairs it generates (Section
[[#results]]).

The novel contributions of this short paper are;
1. an application of automated repair to stripped MIPS ELF files
   recovered from router firmware
2. a modified version of evolutionary program repair which removes the
   requirements for fault localization information, and for a
   regression test suite
3. an application of automated repair to a real-world un-patched
   security exploit resulting in
4. the first demonstration of multiple iterative repairs in a single
   evolutionary run.

In the pursuit of /Reproducible Research/ cite:buckheit1995wavelab
cite:mesirov2010accessible and to encourage researchers to patch
future discovered exploits, we've released a companion version control
repository [fn:1].  This repository contains the instructions, source
code, and tooling needed to extract, execute and repair the binary
NETGEAR router image vulnerabilities.  All software needed to perform
repair work is freely available under open source licensing.
Additionally, the analysis performed in this document and all
supporting figures may be automatically regenerated from new
experimental data using the Org-mode reproducible research framework
cite:schulte2012reproducible-research.

We hope the ability to automatically patch vulnerable closed source
applications without dependence upon the software vendor encourages
users to patch vulnerable systems and researchers to release patches
with exploit announcements.

* Description of Exploits
  :PROPERTIES:
  :CUSTOM_ID: exploits
  :END:
In this work we repair a pair of exploits in version 4 of the popular
NETGEAR WNDR3700 wireless router.  The "shodan" [fn:5] device search
engine returns hundreds of vulnerable publicly accessible WNDR3700
routers at the time of submission cite:shodan.  Both exploits exist in
the router's web server in a binary executable named =net-cgi=, and
both are related to how =net-cgi= handles authentication cite:zcutlip.

1. Any URI starting with the string "BRS" bypasses authentication.

2. Any URI including the string "unauth.cgi" or
   "securityquestions.cgi" bypass authentication even pages of the
   form "http://router/page.html?foo=unauth.cgi".

Many administrative pages start with the "BRS" string, providing
attackers with access to personal information such as user's
passwords, and by accessing the page
"http://router/BRS_02_genieHelp.html" attackers can completely disable
authentication in a manner which is permanent across reboots.

* Repair Technique
To repair the =net-cgi= executable we must extract it and the router
file system from the firmware image distributed by NETGEAR.  Using the
extracted filesystem and executable we construct a test harness used
exercise the exploits in =net-cgi=.  This test harness is used by the
repair algorithm to evaluate candidate repairs and to identify when
repairs to the exploits have been found.

** Router Firmware Extraction and Virtualization
   :PROPERTIES:
   :CUSTOM_ID: firmware
   :END:
NETGEAR distributes firmware holding a full system image for the
WNDR3700 router which include the router file system holding the
vulnerable =net-cgi= executable.  Extraction of the file system may be
accomplished using =binwalk= [fn:2], a firmware extraction tool which
scans the binary data in the firmware file searching for signatures
identifying the types of embedded data sections.  The =binwalk= tool
includes rules for identifying and extracting common embedded data
types, including a squashfs cite:lougher2006squashfs section which in
this case holds the router's file system.

The router runs on a big-endian MIPS architecture.  Using the QEMU
cite:bellard2005qemu system emulator to emulate this architecture a
Debian Linux operating system is run in emulation.  The extracted
router file system is copied into the emulated MIPS Linux system.  A
number of special directories (e.g., =/proc/=, =/dev/= etc...) are
mounted inside the extracted file system and bound to the
corresponding directories on the virtual machine.  At this point
commands may be executed in an environment which closely approximates
the execution environment of the NETGEAR router using the =chroot=
command to confine executable access to within the extracted NETGEAR
file system.

With this accomplished (and with other minor adjustments described in
full in the reproduction information [fn:3]) is it possible to run
NETGEAR router in virtualization.  In particular the web interface of
the router may be accessed either using an external web browser or the
=net-cgi= executable may be called directly from the command line
using a Bash shell script [fn:4].

** Mutation of stripped MIPS ELF Files
   :PROPERTIES:
   :CUSTOM_ID: mips-mutation
   :END:
The repair of ELF format files is an extension of the evolutionary
computation (EC) repair technique introduced in
cite:schulte2013embedded.  Mutation operations are used to modify the
execution behavior of the ELF file.  In this case the =net-cgi= file
is stripped a minimal ELF file which does not include much of the
information assumed to exist by the previous repair technique.

ELF (Executable and Linking Format) cite:tis1995tool files may either
be executed directly or may be linked with other object files to form
an executable or library.  The ELF file contains a number of headers
and tables containing administrative data, and sections holding
program code and data.  The three main administrative elements of an
ELF file are the ELF Header, the section table and the program table
(see Figure [[elf]]).  The ELF Header points to the section table and the
program table, the section table holds information on the layout of
sections in the ELF file on disk, and the program table holds
information on how to copy section from disk into memory for program
execution.

#+name: ELF-layout
#+header: :file (by-backend (latex 'nil) (t "elf-layout.svg"))
#+header: :results (by-backend (pdf "latex") (t "raw"))
#+header: :cache (by-backend (latex "no") (t "yes"))
#+begin_src latex
  \begin{tikzpicture}
    % ELF File
    \node[draw, rectangle, minimum height=14em, minimum width=8em] (whole) at (0,0) {};
    \node[minimum width=8em] (header) at (0,2.125) {ELF Header};
    \draw[thick] (header.south west) -- (header.south east);
    \node[minimum width=8em] (st) at (0,1) {Section Table};
    \node[minimum width=8em] (body1) at (0,-0) {...};
    \node[minimum width=8em] (body2) at (0,-0.5) {Section Data};
    \node[minimum width=8em] (body3) at (0,-1) {...};
    \node[minimum width=8em] (pt) at (0,-2) {Program Table};
    % External Users
    \node[draw, circle, fill=blue!20, minimum width=6em] (linker) at (-3,1) {Linker};
    \node[draw, circle, fill=red!20, minimum width=6em]  (memory) at (3,-2) {Memory};
    % Arrows to Users
    \draw[->,thick] (st.west) to (linker.east);
    \draw[->,thick] (pt.east) to (memory.west);
    % Section Table Arrows
    \draw[->,thick,densely dotted,bend right=90] (body1.east) to (st.east);
    \draw[->,thick,densely dotted,bend right=90] (body2.east) to (st.east);
    \draw[->,thick,densely dotted,bend right=90] (body3.east) to (st.east);
    % Program Table Arrows
    \draw[->,thick,densely dotted,bend right=90] (body1.west) to (pt.west);
    \draw[->,thick,densely dotted,bend right=90] (body2.west) to (pt.west);
    \draw[->,thick,densely dotted,bend right=90] (body3.west) to (pt.west);
  \end{tikzpicture}
#+end_src

#+label: elf
#+Caption: Sections and their uses in an Executable and Linking Format (ELF) file.
#+RESULTS[f4540fe0cc1c41ced82f0223a12facdbe7a720ba]: ELF-layout
[[file:elf-layout.svg]]

While the majority of ELF files include all three of these elements,
only the ELF Header is guaranteed to exist in all cases.  In
executable ELF files the program table is required, and in linkable
files the section table is required.

The previous ELF repair tool required a section table and a section
name string table, which were used to find the =.text= section of the
ELF file where program code is normally stored.  The data in the
=.text= section was then coerced into a "genome" a linear array of
assembly instructions which was modified by the mutation operations.
Our extension of this technique does not require a section table,
instead we build the genome by concatenating the data of every section
in the program table which has a "loadable" type.  These are the
sections whose data are loaded into memory during program execution.

Mutation operations must change program data without corrupting the
structure of the file or breaking the many addresses hard coded into
the program data itself (in general it is impossible to distinguish
between an integer literal and an address in program data).  For this
reason the mutation operations are designed to preserve the absolute
size and the offsets within of the ELF program data.  This is made
easier by the fact that MIPS is a RISC (Reduced Instruction Set
Computing) architecture in which every argumented assembly instruction
is 1 word long cite:hennessy1982mips.  The mutation and crossover
operations used to modify ELF files are shown in Figure [[mutation-ops]].

#+name: mutation-ops
#+header: :file (by-backend (latex 'nil) (t "mut-ops.svg"))
#+header: :results (by-backend (pdf "latex") (t "raw"))
#+header: :cache (by-backend (latex "no") (t "yes"))
#+begin_src latex
  \tikzstyle{asmrow} = [rectangle, draw, minimum width=2em, minimum height=1em]
  \begin{tikzpicture}
    % Mutation
    \foreach \x in {-3.5,-2.5,-0.5,0.5,2.5,3.5}{
      \foreach \y in {-0.8,-0.4,0,0.4,0.8}{
        \node[asmrow,fill=green!40] at (\x,\y) {};
      }
    }
    % Replace
    \node at (-3,1.25) {Replace};
    \node[asmrow,fill=yellow!20] (c-from) at (-3.5,0.4) {};
    \node[asmrow,fill=blue!60] at (-3.5,-0.4) {};
    % replace-after
    \node[asmrow,fill=yellow!20] at (-2.5,0.4) {};
    \node[asmrow,fill=yellow!20] (c-to) at (-2.5,-0.4) {};
    \node[asmrow,fill=green!40]  at (-2.5,-0.8) {};
    % Delete
    \node at (0,1.25) {Delete};
    \node[asmrow,fill=red!40] (d-from) at (-0.5,0) {};
    % delete-after
    \node[asmrow,fill=white] (d-to) at (0.5,0) {\scriptsize{0x0}};
    % Swap
    \node at (3,1.25) {Swap};
    \node[asmrow,fill=yellow!20] (s1-from) at (2.5,0.4) {};
    \node[asmrow,fill=blue!60] (s2-from) at (2.5,-0.4) {};
    % swap-after
    \node[asmrow,fill=blue!60] (s2-to) at (3.5,0.4) {};
    \node[asmrow,fill=yellow!20] (s1-to) at (3.5,-0.4) {};
    % arrows
    \draw[->,thick] (c-from.east) to (c-to.west);
    \draw[->,thick] (d-from.east) to (d-to.west);
    \draw[->,thick] (s1-from.east) to (s1-to.west);
    \draw[->,thick] (s2-from.east) to (s2-to.west);
    % Crossover
    \node at (0,-1.7) {One Point Crossover};
    \foreach \x in {-1.5,1.5}{
      \foreach \y in {-3.8,-3.4,-3,-2.6,-2.2}{
        \node[asmrow,fill=green!40] at (\x,\y) {};
      }
    }
    \foreach \x in {-0.5}{
      \foreach \y in {-3.8,-3.4,-3,-2.6,-2.2}{
        \node[asmrow,fill=blue!60] at (\x,\y) {};
      }
    }
    \draw[->,thick] (-2,-3.2) to (2,-3.2);
    \node[asmrow,fill=blue!60] at (1.5,-3.4) {};
    \node[asmrow,fill=blue!60] at (1.5,-3.8) {};
  \end{tikzpicture}
#+end_src

#+label: mutation-ops
#+Caption: Mutation and Crossover operations in MIPS ELF files.  The program data is represented as a fixed length array of single-word sections.  These operators change these sections maintaining length and offset in the array.
#+RESULTS[a223f0b59d917bf2751392ff703713d47c829371]: mutation-ops
[[file:mut-ops.svg]]

** Lazy on demand Regression Testing
   :PROPERTIES:
   :CUSTOM_ID: lazy
   :END:
We present a novel evolutionary program repair algorithm which does
not require a pre-existing regression test suite.  We adopt the repair
algorithm from cite:forrest2009genetic but instead of assuming that a
regression test suite exists at the beginning of the algorithm, we
only assume that a single test case exists exercising an exploit.
High level pseudocode for the repair algorithm is show in Listing
[[lazy-algorithm]].

We then embark upon an interactive repair process in which the
algorithm fixes every available test (starting with only the exploit),
the user then determines the suitability of the evolved repair either
accepting the repair and terminating the algorithm, or rejecting the
repair and supplying a regression test which the repair fails.  If the
later, then the new test is incorporated into the test suite, and the
repair process continues.  In Section [[#results]] we find that 80% of our
attempts to repair the NETGEAR WNDR3700 exploits did not require any
regression tests be written.

#+label: lazy-algorithm
#+Caption: High-level Pseudocode for interactive lazy-regression-testing repair algorithm.
#+begin_src fundamental -n
  # Input: Vulnerable Program, original: ELF
  # Input: Exploit Test, exploit: ELF -> Fitness
  # Input: Interactive Check, good-enough: ELF -> [ELF -> Fitness]
  # Output: Patched version of Program
  new <- null
  fitness <- null
  suite <- [exploit]
  do
    new <- minimize(evolutionary_subroutine(pop, suite))
    # User evaluates suitability of candidate repair
    new-regression-tests <- good-enough(new)
    suite <- suite ++ new-regression-tests
  until length(new-regression-tests) == 0
  return new
#+end_src

The =evolutionary_subroutine= in Listing [[lazy-algorithm]] has the same
high level organization as the evolutionary repair algorithm presented
in cite:forrest2009genetic, but it uses a /steady state/ evolutionary
computational algorithm cite:Luke2013Metaheuristics for reduced memory
usage and ease of parallelization of fitness evaluation.  High level
pseudocode for the =evolutionary_subroutine= is shown in Listing
[[evolutionary-subroutine]].

#+label: evolutionary-subroutine
#+Caption: High-level Pseudocode for the steady state parallel evolutionary repair subroutine.
#+begin_src fundamental -n
  # Input: Vulnerable Program, original: ELF
  # Input: Test suite, suite: [ELF -> Fitness]
  # Parameters: max-population-size, tournament-size, cross-rate
  # Output: Patched version of Program
  let fitness <- evaluate(original, suite)
  let pop <- max-pop-size copies of <original, fitness>
  do in every thread
    let p <- null
    if random() < cross-rate then
      p <- crossover(tournament(pop,tournament-size,+),
                     tournament(pop,tournament-size,+))
    else
      p <- tournament(pop,tournament-size,+)
    endfi
    p <- mutate(p)
    fitness <- evaluate(suite, p)
    incorporate(pop, <p, fitness>)
    if length(pop) > max-population-size then
      evict(pop, tournament(pop,tournament-size,-))
    endif
  until fitness > length(suite)
  return p
#+end_src

* Repair Demonstration
  :PROPERTIES:
  :CUSTOM_ID: results
  :END:
** Demonstration Methodology
We demonstrate our technique by patching two NETGEAR WNDR3700
exploits.  All repairs were performed on a server-class machine with
32 physical Intel Xeon 2.60GHz cores, Hyper-Threading and 120 GB of
Memory.  To perform fitness evaluations we use 32 QEMU virtual
machines, each running Debian Linux with the NETGEAR router firmware
environment available inside of a =chroot=.

The test framework includes both a host and a guest test script.  The
host script copies a variant of the =net-cgi= executable to the guest
VM, and invokes the guest test script which runs =net-cgi= on the
command line and reports the result of "PASS" "FAIL" or "ERROR" of
each test back to the host test script, which uses these values to
calculate a scalar fitness for the variant.

We report the results of 10 repair attempts, each following the high
level algorithm shown in Listing [[lazy-algorithm]] and using the
following EC parameters.

*** Repair Parameters
Repair was run using the parameters shown in Table [[parameters]].  The
maximum population size was 512 individuals, selection is performed
using a tournament size of 2.  When the population overflows the
maximum population size, an individual is selected for eviction using
a negative tournament of size 2.  Newly selected individuals are
crossed over $\frac{2}{3}$'s of the time.

#+label: parameters
#+Caption: The parameters used to evolve repairs to the NETGEAR WNDR3700 exploits.
| parameter           |         value |
|---------------------+---------------|
| max-population-size |           512 |
| tournament-size     |             2 |
| cross-rate          | $\frac{2}{3}$ |

These parameters differ significantly from those used in previous EC
repair algorithms cite:forrest2009genetic
cite:legoues2011systematicstudy cite:le2012representations in that we
use larger populations (of 512 instead of 40 individuals), running for
many more fitness evaluations (\leq100,000 instead of \leq400).  The
parameters used in this paper are more inline with traditional EC
parameters given the size of the software genome, and allow our
technique to overcome the lack of any fault localization information.

The increased memory required by the larger population size is offset
by the use of a steady state EC algorithm, and the increased
computational demand of the greater number of fitness evaluations is
offset by parallelization of fitness evaluation.

*** Repair Runtime
The repair algorithm itself uses 32 threads for parallel fitness
evaluation.  Each thread is paired with a single QEMU VM on which it
tests fitness.  When any thread finds a repair the inner repair loop
(=evolutionary_subroutine=) of the algorithm terminates globally and
the candidate repair is presented to the user (line 11 of Listing
[[lazy-algorithm]]).

The time taken to perform a fitness evaluation varies with the size of
the regression suite.  Table [[test-speed]] shows the average number of
fitness evaluations performed in our setup per minute over a variety
of regression test sizes.

#+label: test-speed
#+Caption: Using 32 virtual machines to evaluate fitness in parallel we are able to perform the following number of fitness evaluation per minute as a function of regression suite size.
| suite size                  |    0 | 1 | 5 | 10 |
|-----------------------------+------+---+---+----|
| evals per minute w/32 cores | TODO |   |   |    |

# Alternate:
# 
# - graph 1
#   - points -- number of regression tests added (and runtime)
#   - x axis -- coverage of repair (% instructions sampled)
#   - y axis -- functionality of repair (% pages successfully served)

** Analysis of Repairs
*** Iterative Repair
The repairs required two distinct fixes to two different exploits in a
single long evolutionary run.  This is an instance of "iterative
repair" which has not previously been observed in the repair of
real-world extant software.

#+name: fitness-by-time-graph
#+headers: :file (by-backend (latex 'nil) (t "fitness-improvement.svg"))
#+headers: :cache yes
#+begin_src gnuplot
  set title 'Fitness Improvement Over Time w/o Regression Test'
  set ytics 1
  set xtics rotate by -45
  set key outside
  set ylabel 'Mean Population Fitness'
  set xlabel 'Fitness Evaluations'
  plot for [run in "0 1 2 3 4 5 6 7 8 9"] \
       "<(awk '{for(i=2;i<=NF;i++){mean+=$i};mean=(mean/(NF-1));print $1, mean}' ../results/1-".run."/stats.txt)" \
       using 1:2 with lines title "run:".run
#+end_src

#+Caption: Mean fitness as a function of the number of fitness evaluations.  Collected over 10 runs using only the two exploits to access variant fitness.  The two separate fitness plateaus are clearly visible.
#+RESULTS[3555c0ce22627902b7db6dcaf72d888680be0914]: fitness-by-time-graph
[[file:fitness-improvement.svg]]

*** Minimization Impact
In many cases the initial evolved repair broke untested behavior.  For
example evolved repairs sometimes worked when =net-cgi= was called
directly on the command line but not through the embedded [[http://wiki.openwrt.org/doc/uci/uhttpd][µHTTPd]]
webserver, or the evolved file failed to serve pages not used in the
exploit test.  As shown in Table [[minimized-stats]], in most cases the
minimized version of the evolved executable fixed all of the
regressions found in the evolved repair.  The functionality numbers in
Table [[minimized-stats]] were generated using a hand-written regression
test suite.

#+label: minimized-stats
#+Caption: Size and functionality of evolved repair before and after minimization.
| run id | total fitness evals | tests un-minimized | tests minimized |
|--------+---------------------+--------------------+-----------------|
|      0 |               90405 |                  8 |              22 |
|      1 |               17231 |                 22 |              22 |
|      2 |               26879 |                 21 |              22 |
|      3 |               23764 |                 19 |              22 |
|      4 |               47906 |                  6 |               6 |
|      5 |               13102 |                 16 |              22 |
|      6 |               76960 |                 17 |              22 |
|      7 |               11831 |                 20 |              22 |
|      8 |                2846 |                 14 |              14 |
|      9 |               25600 |                 21 |              22 |

*** Repair Size
The initial evolved repair differed from the original at 789 distinct
locations (measured with a unified diff), the minimized differed from
the original at 2 such locations.

: TODO

* Related Work
** Security
The former increases the number of attacks in the short term
cite:arora2006does, while the later risks the vendor ignoring the
exploit extending the life of the exploit (e.g., Oracle reportedly
waited months after researchers privately reported a bug in Java while
thousands of users were attacked before releasing a fix
cite:greenberg2012oracle).

In 2002, special advisor for cyberspace security to then President
Bush, Richard Clarke said "It is irresponsible and... extremely
damaging to release information before the patch is out."  However
there are instances when waiting to report may cause more damage and
the question of when to report an exploit has been studied is not
easily decidable in all cases cite:arora2008optimal.

Software vendors commonly delay releasing patches to security
exploits.  Microsoft waits until the second Tuesday of every month
(known as "Patch Tuesday") to release security patches
cite:lemos2003microsoft, leading malicious users to release new
exploits on the second Wednesday of every month (known as "Exploit
Wednesday") to maximize the time before a patch is released.

In a study of high and medium risk vulnerabilities in Microsoft and
Apple products between 2002 and 2008, ~10% of vulnerabilities were
found not to be patched within 150 days of disclosure, and on any
given date \sim10 vulnerabilities and >20 vulnerabilities were public and
un-patched for Microsoft and Apple respectively cite:frei20080.

** EC
TODO: EC background

** Automated Program Repair
- genprog
- clearview
- semfix

* Discussion
This technique demonstrates the current ability of end users to fix
software exploits in embedded devices without any special information
or help from the software vendor.

Estimate the amount of money cost by delay in release of vendor
patches?

** Threats to Validity
This initial work is based upon a single exploit repair so it is
possible that the results indicating the effectiveness of repair
without any regression test suite will not generalize.  However, the
authors do not believe that these results are based on any property
unique to the NETGEAR exploits, rather we believe that the ability of
the evolutionary repair algorithm to find functional repairs without
the use of any regression test suite is due to both the beneficial
impact of minimization, and to the natural mutational robustness of
software (cf. cite:schulte2013software).  Specifically in
cite:schulte2013software Schulte et al. find that the functionality of
software mutants differs by only ~60% between software tested with a
null regression test suites and software tested with the best
obtainable quality regression test suites.

** Next Steps
- operation directly on a binary image
  - would require better virtualization
  - would require better fault localization
- proactive hardening
  - shutting off (read:breaking) insecure functionality such as
    password reset
  - combination with a fuzz tester in a closed exploit/repair loop
- distributed diversity
  - self certifying patches

* Acknowledgments
Foremost we'd like to thank Zachary Cutlip who analyzed and announced
the NETGEAR exploits, and who helped us to reproduce the exploits
locally.  Without his help this work would not have been possible.  We
would also like to thank Mark Harman for discussion of program repair
without a regression test suite, and Stephen Harding for initially
formulating the interactive lazy regression repair algorithm.

Also, GRANTS GRANTS GRANTS.

#+BIBLIOGRAPHY: netgear-repair plain

* Footnotes

[fn:1] https://github.com/eschulte/netgear-repair

[fn:2] http://binwalk.org

[fn:3] http://eschulte.github.io/netgear-repair/INSTRUCTIONS.html

[fn:4] https://github.com/eschulte/netgear-repair/blob/master/bin/test-cgi

[fn:5] http://www.shodanhq.com/search?q=wndr3700v4+http

